# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d425b06f5e3a3e192637857e6f2c12232702bd20b005cb8314c9a3be6c478ec75d6d7bb5bb08c58a4c71f3115d5af2f85bd7a94195a23a1b79fa1b598f0aca82

test:
  secret_key_base: a3528d7e218ad2bbdf6c4ecc846b5c2b10f630bdb24d97e07702a4adcf89b4ee997dc904fd7490268c722ad81a760091d2167cdcbb66efec69ac7f554a88b611

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
